version: 2.1

orbs:
  # Version 3.2.4 is the "new" uploader, but it's a 50 MB Node.js *binary* and
  # doesn't work on ARM64 Linux (or ARM Macs, or FreeBSD for that matter) and
  # nobody seems to care. Issues opened since Septembe 2021:
  #   https://github.com/codecov/uploader/issues/347
  #   https://github.com/codecov/uploader/issues/523
  #   https://github.com/codecov/uploader/issues/849
  # The old 1.1.1 still seems to work even though codecov got removed from pip
  # on 2023-04-14.
  codecov: codecov/codecov@1.1.1

executors:
  ubuntu-18_04:
    docker:
    - image: ubuntu:bionic-20220427
  # Anything below 12.5.1 is deprecated as of August 2023
  xcode-12_5:
    macos:
      xcode: 12.5.1
  emscripten:
    docker:
    # 1.39.0 is the oldest on Docker. Anything before 1.39.2 is useless as emar
    # randomly asserts: https://github.com/emscripten-core/emscripten/pull/9742
    # Then, anything before 1.39.6 is useless as well because emar has a
    # filesystem race and randomly complains that a file doesn't exist:
    # https://github.com/mosra/magnum/issues/413,
    # https://github.com/emscripten-core/emscripten/pull/10161
    #
    # Regarding SIMD, while 1.39.6 supports some WIP variant of it, the
    # finalized support is only since 2.0.18 (and then the first non-broken
    # emsdk is 2.0.25). But emsdk ships with Node.js 14, and only Node.js 15
    # supports intrinsics that Emscripten 2.0.18 can produce, so there's no
    # point in even trying, we wouldn't be able to run the tests anyway.
    # TODO: revisit when https://github.com/emscripten-core/emsdk/issues/1064
    #   or any other referenced issues are finally resolved
    - image: emscripten/emsdk:1.39.6-upstream
  python-3_6:
    docker:
    - image: python:3.6.12
  android-29:
    machine:
      image: android:202102-01
  arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium

commands:
  install-base-linux:
    parameters:
      extra:
        type: string
        default: ""
    steps:
    - run:
        # TODO when switching to the new codecov uploader, gpg and git needs to
        #   be installed as well
        name: Update apt and install base packages
        command: |
          apt update
          if [[ "$CMAKE_CXX_FLAGS" == *"--coverage"* ]]; then export LCOV_PACKAGES="lcov curl"; fi
          # libidn11 needed by CMake
          apt install -y ninja-build libidn11 $LCOV_PACKAGES << parameters.extra >>

  install-base-linux-arm64:
    parameters:
      extra:
        type: string
        default: ""
    steps:
    - run:
        name: Update apt and install base packages
        # Compared to Docker images this needs sudo
        command: |
          sudo apt update
          if [[ "$CMAKE_CXX_FLAGS" == *"--coverage"* ]]; then export LCOV_PACKAGES="lcov curl"; fi
          sudo apt install -y ninja-build gcc cmake $LCOV_PACKAGES << parameters.extra >>

  # TODO this might get resolved with 1.11.1:
  #   https://github.com/ninja-build/ninja/pull/1827
  #   https://github.com/ninja-build/ninja/pull/2174
  # But wouldn't it build too slow then? Heh
  cap-ninja-jobs:
    parameters:
      count:
        type: integer
        # It reports 36 cores and ninja goes with 38 currently, RAM fluctuates
        # from 3 to 70 GB.
        default: 24
    steps:
    - run:
        name: Query CPU cores, default Ninja parallelism and available RAM, cap jobs
        command: |
          nproc
          ninja --help 2>&1 | grep "N jobs in parallel" || true
          free
          echo "export NINJA_JOBS=-j<< parameters.count >>" >> $BASH_ENV

  install-base-macos:
    parameters:
      extra:
        type: string
        default: ""
    steps:
    - run:
        name: Install base packages
        # As usual, homebrew takes five minutes to update and then explodes in
        # a spectacular way. How is this acceptable?!
        command: |
          if [[ "$CMAKE_CXX_FLAGS" == *"--coverage"* ]]; then export LCOV_PACKAGES="lcov"; fi
          HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake ninja $LCOV_PACKAGES << parameters.extra >>

  install-base-android:
    steps:
    - run:
        name: Create Android 29 x86 AVD
        command: |
          SYSTEM_IMAGES="system-images;android-29;default;x86"
          sdkmanager "$SYSTEM_IMAGES"
          echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
    - run:
        name: Launch Android emulator
        command: |
          emulator -avd test -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        background: true
    - run:
        name: Update apt and install base packages
        # Compared to Docker images this needs sudo
        command: |
          sudo apt update
          sudo apt install -y ninja-build

  install-gcc-4_8:
    steps:
    - run:
        name: Install GCC 4.8
        # For some reason, CMake needs a working C compiler, so provice CC as
        # well for the case when default gcc isn't installed.
        command: |
          apt install -y g++-4.8
          echo 'export CC=gcc-4.8' >> $BASH_ENV
          echo 'export CXX=g++-4.8' >> $BASH_ENV

  # While we want to make sure the project builds on GCC 4.8 as certain
  # embedded toolchains still use it, for Clang we just pick the version
  # available in the oldest supported distro.
  install-clang:
    steps:
    - run:
        # For some reason, CMake needs a working C compiler, so provice CC as
        # well for the case when default gcc isn't installed.
        #
        # The llvm-symbolizer link needs to be set in order to have usable
        # symbols in the output. This affects suppressions as well, meaning
        # they won't work if the symbols are not resolvable. It's not enough to
        # just `export ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer-6.0`
        # because it then complains that
        #
        #   External symbolizer path is set to '/usr/bin/llvm-symbolizer-6.0'
        #   which isn't a known symbolizer. Please set the path to the
        #   llvm-symbolizer binary or other known tool.
        #
        # Probably because because it detects tool type based on the filename?
        # Ugh.
        name: Install Clang
        command: |
          apt install -y clang
          echo 'export CC=clang' >> $BASH_ENV
          echo 'export CXX=clang++' >> $BASH_ENV
          ls -l /usr/bin/llvm-symbolizer-6.0
          ln -s /usr/bin/llvm-symbolizer{-6.0,}

  install-cmake:
    parameters:
      version:
        type: string
      sudo:
        type: string
        default: ""
    steps:
    - run:
        name: Install CMake << parameters.version >>
        command: |
          version_short=<< parameters.version >>
          version_short="${version_short%.*}"
          << parameters.sudo >> apt install -y wget
          mkdir -p $HOME/cmake && cd $HOME/cmake
          wget -nc --no-check-certificate https://cmake.org/files/v$version_short/cmake-<< parameters.version >>-Linux-x86_64.tar.gz
          tar --strip-components=1 -xzf cmake-<< parameters.version >>-Linux-x86_64.tar.gz
          echo 'export PATH=$HOME/cmake/bin:$PATH' >> $BASH_ENV
          source $BASH_ENV
          cmake --version | grep << parameters.version >>
          ctest --version | grep << parameters.version >>

  make-expected-linux-dirs:
    steps:
    - run:
        name: Create files expected by Utility::Path tests on Linux
        command: |
          mkdir -p ~/.config/autostart
          mkdir -p ~/.local

  build:
    parameters:
      script:
        type: string
    steps:
    - checkout
    - run:
        name: Build & test
        command: |
          if [ "$BUILD_STATIC" != "ON" ]; then export BUILD_STATIC=OFF; fi
          if [ "$BUILD_DEPRECATED" != "OFF" ]; then export BUILD_DEPRECATED=ON; fi
          ./package/ci/<< parameters.script >>

  # Extracted outside as it's used by both the lcov step and the `acme` job
  upload-codecov:
    parameters:
      file:
        type: string
    steps:
    # Official docs say "token not needed for public repos", in reality not
    # using the token is "extremely flakey". What's best is that if the upload
    # fails, the damn thing exits with a success error code, and nobody cares:
    # https://github.com/codecov/codecov-circleci-orb/issues/139
    # https://community.codecov.com/t/commit-sha-does-not-match-circle-build/4266
    #
    # Second best thing is that the codecov/upload helper takes a `token`
    # parameter. But the token parameter is an ENVIRONMENT VARIABLE NAME!! So
    # one just *can't* pass the token there. It got changed arbitrarily in
    # https://github.com/codecov/codecov-circleci-orb/pull/93 "because
    # CircleCI docs suggested so", yet all codecov docs suggest just commiting
    # that token directly to the YML files because "it's fine". So if it's
    # fine, why do I have to suffer like this?!
    - run:
        name: Set codecov upload token because everything is a dumpster fire
        # An icing on the cake is that CircleCI commands don't allow setting
        # `environment` for `commands`, only for `jobs`, so I have to do that
        # via bash, and because the environment isn't passsed from a run to
        # run, use the BASH_ENV hack. Mmm. Technology.
        command: |
          echo 'export CODECOV_TOKEN=5f6a19a9-4a9b-4ee8-8a0b-c0cdfbbdcccd' >> "$BASH_ENV"
    - codecov/upload:
        file: << parameters.file >>

  lcov:
    steps:
    - run:
        name: Collect code coverage
        # Keep in sync with PKBUILD-coverage and appveyor-lcov.sh, please
        command: |
          lcov $LCOV_EXTRA_OPTS --directory . --capture --output-file coverage.info > /dev/null
          lcov $LCOV_EXTRA_OPTS --extract coverage.info "*/src/Corrade/*" --output-file coverage.info > /dev/null
          lcov $LCOV_EXTRA_OPTS --remove coverage.info "*/Test/*" --output-file coverage.info > /dev/null
          lcov $LCOV_EXTRA_OPTS --remove coverage.info "*/build/src/Corrade/*" --output-file coverage.info > /dev/null
    - upload-codecov:
        file: coverage.info

jobs:
  linux:
    executor: ubuntu-18_04
    environment:
      CMAKE_CXX_FLAGS: --coverage
      LCOV_EXTRA_OPTS: --gcov-tool /usr/bin/gcov-4.8
      CONFIGURATION: Debug
    steps:
    # Install also Git so we verify that Git version embedding works
    - install-base-linux:
        extra: git
    # OOMs during compilation of Strided[Bit]ArrayViewTest
    # TODO revisit once deprecated includes are dropped (non-deprecated build
    # doesn't fail), https://github.com/mosra/corrade/pull/140 may also help?
    - cap-ninja-jobs
    - install-gcc-4_8
    - install-cmake:
        version: "3.5.2"
    - make-expected-linux-dirs
    - build:
        script: unix-desktop.sh
    - lcov

  linux-arm64:
    executor: arm64
    environment:
      CMAKE_CXX_FLAGS: --coverage
      CONFIGURATION: Debug
    steps:
    # Not installing the old GCC 4.8 and CMake 3.5 to speed up. These are
    # tested more than enough on other jobs.
    - install-base-linux-arm64
    - make-expected-linux-dirs
    - build:
        script: unix-desktop.sh
    - lcov

  linux-static:
    executor: ubuntu-18_04
    environment:
      # STUPID yml interprets unquoted ON as a boolean
      # https://stackoverflow.com/questions/53648244/specifying-the-string-value-yes-in-a-yaml-property
      BUILD_STATIC: "ON"
      CMAKE_CXX_FLAGS: --coverage
      LCOV_EXTRA_OPTS: --gcov-tool /usr/bin/gcov-4.8
      CONFIGURATION: Debug
    steps:
    - install-base-linux
    # OOMs during compilation of Strided[Bit]ArrayViewTest
    # TODO revisit once deprecated includes are dropped (non-deprecated build
    # doesn't fail), https://github.com/mosra/corrade/pull/140 may also help?
    - cap-ninja-jobs
    - install-gcc-4_8
    - install-cmake:
        version: "3.5.2"
    - make-expected-linux-dirs
    - build:
        script: unix-desktop.sh
    - lcov

  linux-nondeprecated:
    executor: ubuntu-18_04
    environment:
      # STUPID yml interprets unquoted OFF as a boolean
      BUILD_DEPRECATED: "OFF"
      CMAKE_CXX_FLAGS: -DCORRADE_NO_ASSERT
      CONFIGURATION: Release
    steps:
    - install-base-linux
    - install-gcc-4_8
    - install-cmake:
        version: "3.5.2"
    - make-expected-linux-dirs
    - build:
        script: unix-desktop.sh

  linux-sanitizers:
    executor: ubuntu-18_04
    environment:
      CMAKE_CXX_FLAGS: -fsanitize=address
      CONFIGURATION: Debug
    steps:
    - install-base-linux
    - install-clang
    - install-cmake:
        version: "3.5.2"
    - make-expected-linux-dirs
    - build:
        script: unix-desktop.sh

  linux-threadsanitizer:
    executor: ubuntu-18_04
    environment:
      CMAKE_CXX_FLAGS: -fsanitize=thread
      CONFIGURATION: Debug
    steps:
    - install-base-linux
    - install-clang
    - install-cmake:
        version: "3.5.2"
    - make-expected-linux-dirs
    - build:
        script: unix-desktop.sh

  macos:
    executor: xcode-12_5
    environment:
      CMAKE_CXX_FLAGS: --coverage
      CONFIGURATION: Debug
    steps:
    - install-base-macos
    - build:
        script: unix-desktop.sh
    - lcov

  macos-static:
    executor: xcode-12_5
    environment:
      # STUPID yml interprets unquoted ON as a boolean
      BUILD_STATIC: "ON"
      CMAKE_CXX_FLAGS: --coverage
      CONFIGURATION: Debug
    steps:
    - install-base-macos
    - build:
        script: unix-desktop.sh
    - lcov

  emscripten:
    executor: emscripten
    steps:
    - install-base-linux
    - build:
        script: emscripten.sh

  android-x86:
    executor: android-29
    steps:
    - install-base-android
    # We need ctest --timeout for flaky adb push, which is since 3.17. The
    # image had 3.16.3 by default, so it's just a small jump.
    - install-cmake:
        version: "3.17.5"
        sudo: sudo
    - build:
        script: android-x86.sh

  ios:
    executor: xcode-12_5
    environment:
      # Yep, xcodebuild is beyond stupid and just DOESN'T build in parallel by
      # default. The default medium resource class has 4 CPUs and Ninja uses
      # -j6, so do the same for xcodebuild.
      XCODE_JOBS: 6
    steps:
    - install-base-macos:
        extra: xcbeautify
    - build:
        script: ios-simulator.sh

  # Python preprocessor for magnum-singles, for a lack of better name
  acme:
    executor: python-3_6
    steps:
    - run:
        name: Install coverage
        command: pip install coverage
    - checkout
    - run:
        name: Run tests and collect coverage
        working_directory: src/acme
        command: |
          coverage run -m unittest
          coverage xml
    - upload-codecov:
        file: src/acme/coverage.xml

workflows:
  version: 2
  build:
    # While there's no actual execution or data dependency between the jobs,
    # this is done in order to reduce unnecessary credit usage. The base and
    # non-deprecated Linux builds are taken as the main sanity checks. Only
    # if they pass, the rest of the jobs gets gradually executed, with further
    # dependencies especially for the macOS jobs that take the most credits.
    jobs:
    - linux
    - linux-nondeprecated
    - linux-arm64:
        requires:
        - linux
        - linux-nondeprecated
    - linux-static:
        requires:
        - linux
        - linux-nondeprecated
    - linux-sanitizers:
        requires:
        - linux
        - linux-nondeprecated
    - linux-threadsanitizer:
        requires:
        - linux-sanitizers
    - macos:
        requires:
        - linux
        - linux-nondeprecated
    - macos-static:
        requires:
        - macos
        - linux-static
    - emscripten:
        requires:
        - linux-static
    - android-x86:
        requires:
        - linux-static
        - linux-arm64
    - ios:
        requires:
        - macos-static
        - linux-arm64
    - acme
