#define CONFIGURATION_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/ConfigurationTestFiles/"
#define CONFIGURATION_WRITE_TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/ConfigurationTestFiles/"

#define DIRECTORY_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/DirectoryTestFiles"
#define DIRECTORY_WRITE_TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/DirectoryTestFiles"

#define RESOURCE_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/ResourceTestFiles/"

#define TRANSLATOR_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/TranslatorTestFiles/"
